name: Samsung Exynos9820 Kernel Build

on:
  workflow_dispatch:
    inputs:
      KSU:
        description: 'Do you want to include KernelSU?'
        required: true
        type: choice
        options:
          - y
          - n
jobs:
  build:
    strategy:
      matrix:
        device: [beyond0lte, beyond0lteks, beyond1lte, beyond1lteks, beyond2lte, beyond2lteks, beyondx, beyondxks, d1, d1xks, d2s, d2x, d2xks]
    runs-on: ubuntu-latest 

    steps:
    - name: Import kernel source
      uses: actions/checkout@v4  
      
    - name: Install required package
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core flex bison build-essential curl \
          zlib1g-dev libc6-dev-i386 lib32z1-dev libncurses5-dev make automake \
          zip unzip p7zip-full tar lz4 xz-utils zlib1g-dev uuid-dev libssl-dev
          checkinstall libncurses-dev libsqlite3-dev tk-dev libgdbm-dev \
          libbz2-dev libffi-dev libreadline-dev libdb-dev wget
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb  

    - name: Setting permission
      run: |    
        chmod +x *.sh
        chmod -R +x prebuilts/    

    - name: Install Python2
      run: ./python2.sh         

    - name: Cooking Kernel
      run: ./build.sh ${{ matrix.device }} ${{ github.event.inputs.KSU }}

    - name : Upload flashable file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.device }}_Kernel_File
        path: |
          prebuilts/*.tar