name: Kernel Build 

on:
  workflow_dispatch:
    inputs:
      MODEL:
        description: 'Choose Your Device'
        required: true
        type: choice
        options:
          - G970F
          - G970N
          - G973F
          - G973N
          - G975F
          - G975N
          - G977B
          - G977N
          - N970F
          - N971N
          - N975F
          - N976B
          - N976N
      
      ASK_KSU:
        description: 'Do you want to build KernelSU?'
        required: true
        type: choice
        default: 'y'
        options:
          - 'y' # Yes
          - 'n' # No

      CHOOSE_KSU:
        description: 'Choose KernelSU Tool'
        required: false
        type: choice
        default: 'n'
        options:
          - 'n' # KernelSU-Next
          - 'w' # Wild_KSU
          - 's' # SukiSU-Ultra

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: 1. import kernel source
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'     
      
    - name: 2. install package
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git libssl-dev bc flex bison \
          libncurses5-dev libncurses-dev cpio zip unzip \
          python3 curl rsync kmod libelf-dev \
          lz4 tar openssl python3-pip \
          gcc clang curl
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb   

    - name: 3. setting permission
      run: chmod +x build.sh

    - name: 4. kernel build (include KernelSU)
      if: ${{ github.event.inputs.ASK_KSU == 'y' }}
      run: |
        echo "Starting build for ${{ github.event.inputs.MODEL }} with KernelSU (${{ github.event.inputs.CHOOSE_KSU }})"
        
        {
          echo "${{ github.event.inputs.ASK_KSU }}"
          echo "${{ github.event.inputs.CHOOSE_KSU }}"
        } | ./build.sh "${{ github.event.inputs.MODEL }}"

    - name: 5. kernel build (not include KernelSU)
      if: ${{ github.event.inputs.ASK_KSU == 'n' }}
      run: |
        echo "Starting build for ${{ github.event.inputs.MODEL }} without KernelSU"
        echo "${{ github.event.inputs.ASK_KSU }}" | ./build.sh "${{ github.event.inputs.MODEL }}"
        
    - name: 6. Upload Artifacts TWRP Installer
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.MODEL }}_TWRP
        path: gorhanhee/*.zip  
    - name: 7. Upload Artifacts Odin Installer
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.MODEL }}_Odin
        path: gorhanhee/*.tar   
