name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: "Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core flex bison build-essential zip curl \
          zlib1g-dev libc6-dev-i386 lib32z1-dev unzip

      - name: "Import kernel source"
        uses: actions/checkout@v4    

      - name: "Setting permission"
        run: chmod +x build.sh

      - name: "Cooking Kernel Source"
        run: ./build.sh
